name: 'ecommerce_analytics'
description: 'DBT project for ecommerce analytics'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_duckdb'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: analytics