name: 'ecommerce_dbt'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_dbt'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_dbt:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: analytics

seeds:
  ecommerce_dbt:
    +schema: raw_data
    customers:
      +column_types:
        customer_id: integer
        created_at: timestamp
    orders:
      +column_types:
        order_id: integer
        customer_id: integer
        order_date: date
        amount: decimal(10,2)