version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: rental_site
    ports:
        - "5432:5432"