version: 2

models:
  - name: stg_orders
    description: Staged order data from our Kafka stream
    columns:
      - name: order_id
        description: Primary key for orders
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Foreign key to customers
        tests:
          - not_null
      - name: order_date
        description: Date when the order was placed
      - name: status
        description: Order status (completed, returned, etc.)
      - name: amount
        description: Total order amount

  - name: stg_customers
    description: Staged customer data from our Kafka stream
    columns:
      - name: customer_id
        description: Primary key for customers
        tests:
          - unique
          - not_null
      - name: email
        description: Customer email address
        tests:
          - unique
          - not_null
      - name: first_name
        description: Customer first name
      - name: last_name
        description: Customer last name
      - name: created_at
        description: Timestamp when customer account was created
      - name: country
        description: Customer country