version: 2

sources:
  - name: json_files
    schema: main
    tables:
      - name: customers
        description: Raw customer data from JSON files
      - name: orders
        description: Raw order data from JSON files