name: 'ecommerce_pyspark'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_pyspark'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_pyspark:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: analytics

seeds:
  ecommerce_pyspark:
    +schema: raw_data