FROM python:3.9-slim

WORKDIR /app

# Install Kafka Python client and PostgreSQL connector
RUN pip install --no-cache-dir kafka-python psycopg2-binary

# Keep container running
CMD ["tail", "-f", "/dev/null"]